runtime: go112  # or go113 or go114 for Go 1.13 or Go 1.14 (beta)

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  GCLOUD_PROJECT: "grounded-access-123008"

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

  - url: /.*
    script: auto